### ISSUE TITLE
Please update/upgrade to a modern version of gradle/gradlew

### ISSUE THREAD

**Issue by javadba** [jakubdyszkiewicz/naphi#1]
I am quite interested in this project. But there are tough build issues due to the antiquated version of gradle/gradlew.  I am new to kotlin and gradle and have already tried a few approaches that I could find by googling: they have not worked. After upgrading to gradle 6.0 here is what I get

    Could not initialize class org.jetbrains.kotlin.gradle.internal.KotlinSourceSetProviderImplKt

Fixing this would probably take you a small fraction of my effort - but it's your time. Hopefully you'll spare a few minutes ;)

**Comment by jakubdyszkiewicz** [comment]
Hey @javadba,

I'll try to refresh dependencies soon (later today) :)

**Comment by jakubdyszkiewicz** [comment]
Fixed with #2 
let me know if you have more questions!
